#!/usr/bin/env python3
"""Count repository items that are commonly referenced in docs."""

import argparse
import importlib.util
import json
import subprocess
from collections import Counter
from pathlib import Path


def load_gemini_sync_module(repo_root: Path):
    script_path = repo_root / "scripts" / "sync-gemini-skills.py"
    spec = importlib.util.spec_from_file_location("sync_gemini_skills", script_path)
    if not spec or not spec.loader:
        raise RuntimeError(f"Could not load {script_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def git_ls_files(repo_root: Path) -> list[str]:
    result = subprocess.run(
        ["git", "ls-files"],
        cwd=repo_root,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    return [line for line in result.stdout.splitlines() if line]


def collect_counts(repo_root: Path) -> dict:
    sync_module = load_gemini_sync_module(repo_root)
    skills = sync_module.find_skills(repo_root)
    tracked = git_ls_files(repo_root)

    categories = Counter(skill["category"] for skill in skills)
    gemini_mirror = list((repo_root / ".gemini" / "skills").glob("*/SKILL.md"))

    return {
        "skills": {
            "total": len(skills),
            "by_category": dict(sorted(categories.items())),
        },
        "gemini_mirror_skill_links": len(gemini_mirror),
        "python_tools_tracked": sum(1 for path in tracked if path.endswith(".py")),
        "agents_markdown_tracked": sum(
            1 for path in tracked if path.startswith("agents/") and path.endswith(".md")
        ),
        "commands_markdown_tracked": sum(
            1 for path in tracked if path.startswith("commands/") and path.endswith(".md")
        ),
    }


def render_inventory_md(counts: dict) -> str:
    """Render counts as a deterministic, human-readable inventory document.

    Output is a pure function of ``counts`` so CI can regenerate it and assert
    byte-equality against the committed file (Invariant 1: generated-artifact
    drift gate). Never hand-edit the generated file."""
    skills = counts["skills"]
    lines = [
        "# Repository Inventory",
        "",
        "> Generated by `python3 scripts/count-repository-items.py --write`.",
        "> **Do not edit by hand.** CI regenerates this and fails on drift",
        "> (see `documentation/FLEET_QUALITY_INVARIANTS.md`, Invariant 1).",
        "",
        "| Metric | Count |",
        "|--------|-------|",
        f"| Skills (total) | {skills['total']} |",
        f"| Python tools (tracked `*.py`) | {counts['python_tools_tracked']} |",
        f"| Agents (`agents/**/*.md`) | {counts['agents_markdown_tracked']} |",
        f"| Slash commands (`commands/**/*.md`) | {counts['commands_markdown_tracked']} |",
        f"| Gemini mirror skill links | {counts['gemini_mirror_skill_links']} |",
        "",
        "## Skills by domain",
        "",
        "| Domain | Count |",
        "|--------|-------|",
    ]
    for domain, count in skills["by_category"].items():
        lines.append(f"| {domain} | {count} |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Count repository inventory items")
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="Repository root to inspect",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write documentation/INVENTORY.md from current repository state",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if documentation/INVENTORY.md is stale (drift gate)",
    )
    args = parser.parse_args()
    counts = collect_counts(args.repo_root)
    inventory_path = args.repo_root / "documentation" / "INVENTORY.md"

    if args.write:
        inventory_path.parent.mkdir(parents=True, exist_ok=True)
        inventory_path.write_text(render_inventory_md(counts) + "\n", encoding="utf-8")
        print(f"Wrote {inventory_path.relative_to(args.repo_root)}")
        return

    if args.check:
        expected = render_inventory_md(counts) + "\n"
        actual = inventory_path.read_text(encoding="utf-8") if inventory_path.exists() else ""
        if actual != expected:
            print(
                "ERROR: documentation/INVENTORY.md is stale. "
                "Run `python3 scripts/count-repository-items.py --write` and commit.",
            )
            raise SystemExit(1)
        print("INVENTORY.md is up to date.")
        return

    print(json.dumps(counts, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
