# ruff: noqa: F403, F405, E501, E402
import sys as _spsys
import pathlib as _sppath
_spsys.path.insert(0, str(_sppath.Path(__file__).resolve().parent))
from comparison_matrix_builder_base import *  # noqa: F403,E402
# fmt: off
from comparison_matrix_builder_p1 import STATUS_LABEL, STATUS_TEXT  # noqa: E402,E501
# fmt: on


def build_markdown(result: dict) -> str:
    m    = result["meta"]
    rows = result["features"]
    comp = m["competitors"]

    lines = []
    lines.append(f"# Feature Comparison: {m['your_product']} vs Competitors\n")
    lines.append(f"_Generated by comparison_matrix_builder.py — {m['total_features']} features, "
                 f"{len(comp)} competitor(s)_\n")

    # Summary table
    lines.append("## Competitive Score Summary\n")
    lines.append("| Competitor | You Win | Tie | You Lose | Win % | Verdict |")
    lines.append("|---|---|---|---|---|---|")
    for c, s in result["competitor_scores"].items():
        lines.append(f"| {c} | {s['wins']} | {s['ties']} | {s['losses']} | "
                     f"**{s['win_pct']}%** | {s['verdict']} |")
    lines.append(f"\n**Overall win rate: {m['overall_win_pct']}% — {m['verdict']}**\n")

    # Feature matrix by category
    lines.append("## Feature Matrix\n")
    header = f"| Feature | {m['your_product']} | " + " | ".join(comp) + " | Notes |"
    sep    = "|---|---|" + "|".join(["---"] * len(comp)) + "|---|"
    lines.append(header)
    lines.append(sep)

    current_cat = None
    for r in rows:
        cat = r["category"]
        if cat != current_cat:
            lines.append(f"| **{cat}** | | " + " | ".join([""] * len(comp)) + " |  |")
            current_cat = cat
        you_icon  = STATUS_LABEL[r["your_status"]]
        comp_icons = " | ".join(STATUS_LABEL[r["competitors"].get(c, "no")] for c in comp)
        note      = r["notes"] or ""
        # Highlight row if it's a unique advantage
        fname = f"**{r['name']}**" if r["advantage"] > 0 else r["name"]
        lines.append(f"| {fname} | {you_icon} | {comp_icons} | {note} |")

    lines.append("")

    # Advantages
    if result["advantages"]:
        lines.append("## ✅ Your Advantages\n")
        for a in result["advantages"]:
            lines.append(f"- {a}")
        lines.append("")

    # Gaps
    if result["gaps"]:
        lines.append("## ⚠️ Feature Gaps (competitors ahead)\n")
        for g in result["gaps"]:
            lines.append(f"- {g}")
        lines.append("")

    # Legend
    lines.append("## Legend\n")
    for k, v in STATUS_LABEL.items():
        lines.append(f"- {v} {STATUS_TEXT[k]}")
    lines.append("")

    return "\n".join(lines)
def pretty_print(result: dict) -> None:
    m = result["meta"]
    print("\n" + "=" * 70)
    print(f"  COMPETITIVE MATRIX: {m['your_product'].upper()} vs {', '.join(m['competitors'])}")
    print("=" * 70)
    print(f"\n  Total features analysed : {m['total_features']}")
    print(f"  Overall win rate        : {m['overall_win_pct']}%  ({m['verdict']})")

    print(f"\n{'─'*70}")
    print(f"  {'COMPETITOR':<22}  {'WIN%':>5}  {'WINS':>5}  {'TIES':>5}  {'LOSSES':>7}  VERDICT")
    print(f"{'─'*70}")
    for c, s in result["competitor_scores"].items():
        bar = "█" * (s["win_pct"] // 10) + "░" * (10 - s["win_pct"] // 10)
        print(f"  {c:<22}  {s['win_pct']:>4}%  {s['wins']:>5}  {s['ties']:>5}  "
              f"{s['losses']:>7}  {bar}  {s['verdict']}")

    print(f"\n{'─'*70}")
    col_w = 20
    header = f"  {'FEATURE':<28} | {'YOU':^8}"
    for c in m["competitors"]:
        header += f" | {c[:8]:^8}"
    print(header)
    print("─" * (30 + 11 * (1 + len(m["competitors"]))))

    current_cat = None
    for r in result["features"]:
        if r["category"] != current_cat:
            print(f"\n  [{r['category']}]")
            current_cat = r["category"]
        you_icon  = STATUS_LABEL[r["your_status"]]
        line = f"  {'  '+r['name']:<28} | {you_icon:^8}"
        for c in m["competitors"]:
            ci = STATUS_LABEL[r["competitors"].get(c, "no")]
            line += f" | {ci:^8}"
        if r["advantage"] > 0:
            line += "  ← advantage"
        elif r["advantage"] < 0:
            line += "  ← gap"
        print(line)

    print(f"\n  ✅ YOUR ADVANTAGES  ({len(result['advantages'])} features)")
    for a in result["advantages"]:
        print(f"    • {a}")

    print(f"\n  ⚠️  FEATURE GAPS  ({len(result['gaps'])} features)")
    for g in result["gaps"]:
        print(f"    • {g}")

    print(f"\n  Legend: {STATUS_LABEL['full']} Full  {STATUS_LABEL['partial']} Partial  "
          f"{STATUS_LABEL['no']} No  {STATUS_LABEL['planned']} Planned\n")
DEMO_DATA = {
    "your_product": "SwiftBase",
    "features": [
        {"name": "SSO / SAML",          "category": "Security",     "weight": 3, "your_status": "full",    "competitors": {"AcmeSaaS": "no",      "ProStack": "partial"}, "notes": "All plans"},
        {"name": "2FA / MFA",            "category": "Security",     "weight": 3, "your_status": "full",    "competitors": {"AcmeSaaS": "full",    "ProStack": "full"},    "notes": ""},
        {"name": "SOC 2 Type II",        "category": "Security",     "weight": 3, "your_status": "planned", "competitors": {"AcmeSaaS": "full",    "ProStack": "no"},      "notes": "Q3 target"},
        {"name": "Role-based access",    "category": "Security",     "weight": 2, "your_status": "full",    "competitors": {"AcmeSaaS": "partial", "ProStack": "full"},    "notes": ""},
        {"name": "REST API",             "category": "Integrations", "weight": 3, "your_status": "full",    "competitors": {"AcmeSaaS": "full",    "ProStack": "full"},    "notes": ""},
        {"name": "GraphQL API",          "category": "Integrations", "weight": 2, "your_status": "full",    "competitors": {"AcmeSaaS": "no",      "ProStack": "partial"}, "notes": ""},
        {"name": "Zapier Integration",   "category": "Integrations", "weight": 2, "your_status": "partial", "competitors": {"AcmeSaaS": "full",    "ProStack": "full"},    "notes": "10 zaps only"},
        {"name": "Webhooks",             "category": "Integrations", "weight": 2, "your_status": "full",    "competitors": {"AcmeSaaS": "full",    "ProStack": "no"},      "notes": ""},
        {"name": "Custom domain",        "category": "Branding",     "weight": 2, "your_status": "full",    "competitors": {"AcmeSaaS": "partial", "ProStack": "full"},    "notes": ""},
        {"name": "White-label / rebrand","category": "Branding",     "weight": 2, "your_status": "full",    "competitors": {"AcmeSaaS": "no",      "ProStack": "partial"}, "notes": "Agency plan"},
        {"name": "Priority support",     "category": "Support",      "weight": 2, "your_status": "full",    "competitors": {"AcmeSaaS": "partial", "ProStack": "full"},    "notes": "24/7"},
        {"name": "Dedicated CSM",        "category": "Support",      "weight": 2, "your_status": "no",      "competitors": {"AcmeSaaS": "full",    "ProStack": "full"},    "notes": "Enterprise only"},
        {"name": "SLA guarantee",        "category": "Support",      "weight": 3, "your_status": "no",      "competitors": {"AcmeSaaS": "full",    "ProStack": "no"},      "notes": "Roadmap"},
    ],
}
